services:
  db:
    image: postgres
    container_name: InnoQuest
    environment:
      POSTGRES_USER: ${POSTGRES_USER}
      POSTGRES_PASSWORD: ${POSTGRES_PASSWORD}
      POSTGRES_DB: ${POSTGRES_DB}
    ports:
      - "5432:5432"
    volumes:
      - innoquest:/var/lib/postgresql/data
    restart: always

volumes:
  innoquest: